In [1]:
from air_hockey_challenge.framework.air_hockey_challenge_wrapper import AirHockeyChallengeWrapper

from air_hockey_challenge.environments.iiwas.env_hitting import AirHockeyHit
from air_hockey_agent.agent_builder_ddpg_hit import build_agent
import numpy as np

pybullet build time: May 20 2022 19:44:17


In [2]:
env = AirHockeyChallengeWrapper(env="7dof-hit", interpolation_order=3, debug=False)
# policy = build_agent(env.env_info)
policy = build_agent(env.env_info) 

In [3]:
state, done = env.reset(), False
env.render()


In [4]:
action = policy.draw_action(np.array(state))

# Perform action
next_state, reward, done, _ = env.step(action)
env.render()

In [5]:
next_state

array([ 1.01092272e+00,  3.36833679e-02, -5.17195762e-03, -3.78042692e-01,
       -2.55376565e-01, -2.57616585e-01, -7.34483652e-02, -2.05689578e-01,
        8.63480357e-02, -1.84427438e+00, -3.66915806e-02,  9.60816705e-01,
       -2.35076631e-02, -1.45727843e+01, -2.55890526e-01,  1.14641582e+01,
       -5.63309576e-02,  8.01443930e+00, -5.58031518e-02,  6.08638418e+00,
        2.37373363e+00,  3.90604999e-03,  1.64211777e-01])

In [6]:
policy.get_ee_pose(next_state)

(array([ 0.6570691 , -0.01602344,  0.17382842]),
 array([[-0.8559957 , -0.03371352,  0.51588251],
        [-0.06303962,  0.99723179, -0.03943039],
        [-0.5131251 , -0.06627328, -0.85575141]]))

In [7]:
from air_hockey_challenge.utils.kinematics import inverse_kinematics

In [178]:
des_pos = np.array([0.78,0.00,0.181])
_,x = inverse_kinematics(policy.robot_model, policy.robot_data,des_pos)

In [179]:
x

array([-1.32562380e-17, -3.35883047e-02, -1.24463119e-17, -1.76999920e+00,
       -1.03464779e-17,  7.61726915e-01,  4.75070145e-21])

In [180]:
_

True

In [102]:
action = np.zeros((2,7))
action[0,:] = x[1]
action[1,:] = 0.1

In [134]:
next_state, reward, done, _ = env.step(action)
env.render()

In [16]:
policy.get_ee_pose(next_state)

(array([0.64010856, 0.01666328, 0.1527822 ]),
 array([[-0.86484366, -0.11688435,  0.48824532],
        [-0.12211214,  0.9922888 ,  0.02124982],
        [-0.48696414, -0.04124291, -0.87244768]]))

In [136]:
env.env_info

{'table': {'length': 1.948, 'width': 1.038, 'goal_width': 0.25},
 'puck': {'radius': 0.03165},
 'mallet': {'radius': 0.04815},
 'n_agents': 2,
 'robot': {'n_joints': 7,
  'ee_desired_height': 0.1645,
  'joint_vel_limit': array([[-1.48352986, -1.48352986, -1.74532925, -1.30899694, -2.26892803,
          -2.35619449, -2.35619449],
         [ 1.48352986,  1.48352986,  1.74532925,  1.30899694,  2.26892803,
           2.35619449,  2.35619449]]),
  'joint_acc_limit': array([[-14.83529864, -14.83529864, -17.45329252, -13.08996939,
          -22.68928028, -23.5619449 , -23.5619449 ],
         [ 14.83529864,  14.83529864,  17.45329252,  13.08996939,
           22.68928028,  23.5619449 ,  23.5619449 ]]),
  'base_frame': [array([[ 1.  ,  0.  ,  0.  , -1.51],
          [ 0.  ,  1.  ,  0.  ,  0.  ],
          [ 0.  ,  0.  ,  1.  , -0.1 ],
          [ 0.  ,  0.  ,  0.  ,  1.  ]]),
   array([[-1.  ,  0.  ,  0.  ,  1.51],
          [ 0.  , -1.  ,  0.  ,  0.  ],
          [ 0.  ,  0.  ,  1.  , -0.1 ],


In [162]:
env.env_info['robot']['ee_desired_height']

0.1645

In [161]:
env._mdp_info.observation_space.shape
# env.env_info['rl_info'].action_space.low

(23,)

In [157]:
env.base_env.env_info["rl_info"].observation_space.low.shape

(23,)

In [153]:
import numpy as np
pos_max = env.env_info['robot']['joint_pos_limit'][1]
vel_max = env.env_info['robot']['joint_vel_limit'][1] 
max_ = np.stack([pos_max,vel_max])
max_action  =   max_.reshape(14,)

In [154]:
max_action

array([2.96706   , 2.0944    , 2.96706   , 2.0944    , 2.96706   ,
       2.0944    , 3.05433   , 1.48352986, 1.48352986, 1.74532925,
       1.30899694, 2.26892803, 2.35619449, 2.35619449])

In [169]:
from air_hockey_challenge.utils.transformations import world_to_robot
print(env.env_info['robot']['base_frame'][0])
x = world_to_robot(env.env_info['robot']['base_frame'][0],env.env_info['table']['length'])

[[ 1.    0.    0.   -1.51]
 [ 0.    1.    0.    0.  ]
 [ 0.    0.    1.   -0.1 ]
 [ 0.    0.    0.    1.  ]]


TypeError: object of type 'float' has no len()

In [199]:
import torch
loss = torch.nn.MSELoss(reduction='none')
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5,requires_grad=True)
output = loss(input, target)
# print(output.detach().numpy())
print(output)

tensor([[2.0921, 5.6445, 0.0062, 4.3529, 1.1709],
        [5.9289, 2.4195, 4.5575, 0.4351, 1.1163],
        [3.7259, 0.4411, 2.3772, 3.0531, 3.1126]], grad_fn=<MseLossBackward0>)


In [207]:
output.backward(torch.ones_like(input)*1.0,retain_graph=True)
print(output.grad.data)
# output.grad.data.zero_()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [202]:
print(output)

tensor([[2.0921, 5.6445, 0.0062, 4.3529, 1.1709],
        [5.9289, 2.4195, 4.5575, 0.4351, 1.1163],
        [3.7259, 0.4411, 2.3772, 3.0531, 3.1126]], grad_fn=<MseLossBackward0>)


In [177]:
ee_pos = policy.get_ee_pose(state)[0] 
print(ee_pos)
des_z = env.env_info['robot']['ee_desired_height']
print(des_z)

[ 6.50000005e-01 -1.01327613e-38  1.64500044e-01]
0.1645
